"use client"

import React, { useState, useEffect } from 'react';
import { useUser } from '@clerk/nextjs';
import jsPDF from 'jspdf';
import {
  FileText, Upload, Download, CheckCircle, AlertCircle,
  Loader2, Sparkles, ChevronRight, Star, RefreshCw,
  Shield, ArrowRight
} from 'lucide-react';
import Background from '../../components/Background';
import { fetchWithFallback, MOCK_DATA } from '../lib/api-config';
import Link from 'next/link';

export default function ResumeAnalyser() {
  const { isLoaded, isSignedIn, user } = useUser();
  const [activeTab, setActiveTab] = useState<'analyze' | 'enhance' | 'generate'>('analyze');
  const [resumeText, setResumeText] = useState('');
  const [targetRole, setTargetRole] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState<any>(null);

  // States for Resume Generation
  const [personalInfo, setPersonalInfo] = useState({
    name: '',
    email: '',
    phone: '',
    location: '',
    linkedin: ''
  });
  const [summary, setSummary] = useState('');
  const [experience, setExperience] = useState<any[]>([]);
  const [education, setEducation] = useState<any[]>([]);
  const [skillsList, setSkillsList] = useState('');

  // User consistency sync
  useEffect(() => {
    if (user) {
      setPersonalInfo(prev => ({
        ...prev,
        name: user.fullName || '',
        email: user.primaryEmailAddress?.emailAddress || ''
      }));
    }
  }, [user]);

  // Theme sync
  const [theme, setTheme] = useState('dark');
  useEffect(() => {
    const savedTheme = localStorage.getItem('theme') || 'dark';
    setTheme(savedTheme);
  }, []);

  // -- PDF GENERATION LOGIC --
  const generatePDF = (content: string, type: 'analysis' | 'enhanced' | 'generated') => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;
    let yPosition = 20;

    // Formatting helpers
    const addTitle = (text: string) => {
      if (yPosition > 270) { doc.addPage(); yPosition = 20; }
      doc.setFontSize(24);
      doc.setTextColor(33, 33, 33);
      doc.setFont('helvetica', 'bold');
      doc.text(text, margin, yPosition);
      yPosition += 15;
    };

    const addSection = (text: string) => {
      if (yPosition > 260) { doc.addPage(); yPosition = 20; }
      yPosition += 5;
      doc.setFontSize(14);
      doc.setTextColor(100, 100, 100);
      doc.setFont('helvetica', 'bold');
      doc.text(text.toUpperCase(), margin, yPosition);
      // Underline
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, yPosition + 2, pageWidth - margin, yPosition + 2);
      yPosition += 10;
    };

    const addBody = (text: string, isBold: boolean = false) => {
      if (yPosition > 275) { doc.addPage(); yPosition = 20; }
      doc.setFontSize(11);
      doc.setTextColor(60, 60, 60);
      doc.setFont('helvetica', isBold ? 'bold' : 'normal');

      const cleanText = text.replace(/\*\*/g, '');
      const lines = doc.splitTextToSize(cleanText, maxLineWidth);

      lines.forEach((line: string) => {
        if (yPosition > 280) { doc.addPage(); yPosition = 20; }
        doc.text(line, margin, yPosition);
        yPosition += 6;
      });
      // Extra spacing after paragraphs
      if (!isBold) yPosition += 2;
    };

    // Header based on type
    if (type === 'analysis') {
      addTitle('Resume Analysis Report');
    }

    // Advanced Text Parsing
    const lines = content.split('\n');
    lines.forEach(line => {
      const trimmed = line.trim();
      if (!trimmed) return;

      if (trimmed.startsWith('# ')) {
        addTitle(trimmed.replace('# ', ''));
      } else if (trimmed.startsWith('## ')) {
        addSection(trimmed.replace('## ', ''));
      } else if (trimmed.startsWith('**') && trimmed.endsWith('**')) {
        addBody(trimmed.replace(/\*\*/g, ''), true);
      } else {
        addBody(trimmed.replace(/\*\*/g, '').replace(/- /, '• '));
      }
    });

    // Footer
    const pageCount = doc.internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text(`Generated by The Resume Hub - ${new Date().toLocaleDateString()} - Page ${i}`, margin, 290);
    }

    doc.save(`${type}_resume.pdf`);
  };

  const [certs, setCerts] = useState('');

  const handleAction = async () => {
    // Validation based on active tab
    if (activeTab === 'generate') {
      if (!personalInfo.name || !targetRole) {
        setError("Please fill in at least your Name and Target Role.");
        return;
      }
    } else if (!resumeText || !targetRole) {
      setError("Please fill in both the Target Role and Resume Content.");
      return;
    }

    setLoading(true);
    setError('');
    // RESULT IS NOT NULLIFIED HERE TO KEEP UI STABLE DURING RELOAD
    // setResult(null);

    const userId = user?.username || user?.id || 'user_demo';

    try {
      if (activeTab === 'analyze') {
        const payload = {
          user_id: userId,
          data: {
            resume_text: resumeText,
            target_role: targetRole
          }
        };

        const data = await fetchWithFallback(
          '/api/webhook/resume/analyze',
          {
            method: 'POST',
            body: JSON.stringify(payload)
          },
          MOCK_DATA.resume.analysis
        );
        setResult(data);

      } else if (activeTab === 'enhance') {
        const payload = {
          user_id: userId,
          data: {
            resume_text: resumeText,
            target_role: targetRole
          }
        };

        const data = await fetchWithFallback(
          '/api/webhook/resume/enhance',
          {
            method: 'POST',
            body: JSON.stringify(payload)
          },
          MOCK_DATA.resume.enhanced
        );
        setResult(data);
      } else if (activeTab === 'generate') {
        const payload = {
          user_id: userId,
          data: {
            personal_info: personalInfo,
            summary: summary,
            target_role: targetRole,
            experience: experience.map(exp => ({
              ...exp,
              highlights: typeof exp.highlights === 'string' ? exp.highlights.split('\n').filter(Boolean) : exp.highlights
            })),
            education: education,
            skills: skillsList.split(',').map(s => s.trim()).filter(Boolean),
            certifications: certs.split(',').map(s => s.trim()).filter(Boolean)
          }
        };

        const data = await fetchWithFallback(
          '/api/webhook/resume/generate',
          {
            method: 'POST',
            body: JSON.stringify(payload)
          },
          MOCK_DATA.resume.generate
        );
        setResult(data);

        // CLEAR ALL FIELDS
        setPersonalInfo({ name: '', email: '', phone: '', location: '', linkedin: '' });
        setSummary('');
        setExperience([]);
        setEducation([]);
        setSkillsList('');
        setCerts('');
        setTargetRole('');
      }

    } catch (err) {
      console.error(err);
      setError("Failed to process resume. Please try again.");
    } finally {
      setLoading(false);
    }
  };
  if (!isLoaded) return <div className="min-h-screen flex items-center justify-center"><Loader2 className="animate-spin w-10 h-10 text-purple-500" /></div>;

  return (
    <div className="min-h-screen relative transition-colors duration-300">
      <Background />

      <div className="pt-32 pb-20 px-4 sm:px-6 max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-10 sm:mb-12">
          <div className="inline-flex items-center gap-2 mb-4">
            <Sparkles className="w-5 h-5 sm:w-6 sm:h-6 text-purple-500" />
            <span className="text-xs sm:text-sm font-semibold text-purple-500 uppercase tracking-widest">AI Optimization</span>
          </div>
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4 sm:mb-6 bg-gradient-to-r from-purple-500 via-pink-500 to-cyan-500 bg-clip-text text-transparent leading-tight">
            Resume Intelligence Hub
          </h1>
          <p className="text-base sm:text-xl opacity-70 max-w-2xl mx-auto px-4 sm:px-0">
            Analyze, enhance, and perfect your resume with advanced AI models tailored to your target role.
          </p>
        </div>

        {/* Main Interface */}
        <div className="grid lg:grid-cols-2 gap-8 items-start">

          {/* Input Section */}
          <div className="glass card-shadow rounded-2xl p-8 space-y-6 hover:scale-[1.01] hover:shadow-purple-500/5 transition-all duration-300">

            {/* Tabs */}
            <div className="flex flex-col sm:flex-row gap-2 sm:gap-4 mb-6 sm:mb-8 p-1.5 bg-white/5 rounded-2xl">
              {(['analyze', 'enhance', 'generate'] as const).map((tab) => (
                <button
                  key={tab}
                  onClick={() => { setActiveTab(tab); setResult(null); }}
                  className={`flex-1 py-2.5 sm:py-3 rounded-xl font-bold transition-all text-sm sm:text-base ${activeTab === tab
                    ? 'bg-gradient-to-r from-purple-500 to-pink-500 text-white card-shadow-purple'
                    : 'opacity-50 hover:opacity-100 hover:bg-white/5'
                    }`}
                >
                  {tab === 'analyze' ? "Analyze" : tab === 'enhance' ? "Enhance" : "Generate"}
                </button>
              ))}
            </div>

            {/* Form */}
            <div className="space-y-4">
              {/* Common field for all tabs */}
              <div>
                <label className="block text-sm font-medium opacity-60 mb-2">Target Role</label>
                <input
                  type="text"
                  value={targetRole}
                  onChange={(e) => setTargetRole(e.target.value)}
                  className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 focus:ring-2 focus:ring-purple-500 transition-all outline-none"
                  placeholder="e.g. Senior Backend Engineer"
                />
              </div>

              {activeTab === 'generate' ? (
                <div className="space-y-8">
                  {/* Personal Info */}
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium opacity-60 mb-2">Name</label>
                      <input
                        type="text"
                        className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3"
                        value={personalInfo.name}
                        onChange={e => setPersonalInfo({ ...personalInfo, name: e.target.value })}
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium opacity-60 mb-2">Email</label>
                      <input
                        type="email"
                        className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3"
                        value={personalInfo.email}
                        onChange={e => setPersonalInfo({ ...personalInfo, email: e.target.value })}
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium opacity-60 mb-2">Phone</label>
                      <input
                        type="text"
                        className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3"
                        value={personalInfo.phone}
                        onChange={e => setPersonalInfo({ ...personalInfo, phone: e.target.value })}
                        placeholder="555-0123"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium opacity-60 mb-2">Location</label>
                      <input
                        type="text"
                        className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3"
                        value={personalInfo.location}
                        onChange={e => setPersonalInfo({ ...personalInfo, location: e.target.value })}
                        placeholder="San Francisco, CA"
                      />
                    </div>
                    <div className="col-span-2">
                      <label className="block text-sm font-medium opacity-60 mb-2">LinkedIn URL</label>
                      <input
                        type="text"
                        className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3"
                        value={personalInfo.linkedin}
                        onChange={e => setPersonalInfo({ ...personalInfo, linkedin: e.target.value })}
                        placeholder="linkedin.com/in/username"
                      />
                    </div>
                  </div>

                  {/* Summary */}
                  <div>
                    <label className="block text-sm font-medium opacity-60 mb-2">Professional Summary</label>
                    <textarea
                      className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 h-24"
                      value={summary}
                      onChange={e => setSummary(e.target.value)}
                      placeholder="Briefly describe your career goals and key strengths..."
                    />
                  </div>

                  {/* Experience */}
                  <div className="space-y-4">
                    <div className="flex justify-between items-center">
                      <label className="text-sm font-medium opacity-60">Experience</label>
                      <button
                        onClick={() => setExperience([...experience, { title: '', company: '', duration: '', highlights: '' }])}
                        className="text-xs text-purple-400 hover:text-purple-300 font-bold"
                      >
                        + Add Job
                      </button>
                    </div>
                    {experience.map((exp, i) => (
                      <div key={i} className="p-4 rounded-xl bg-white/5 border border-white/10 space-y-3">
                        <div className="grid grid-cols-2 gap-3">
                          <input
                            placeholder="Job Title"
                            className="bg-transparent border-b border-white/10 py-1 outline-none"
                            value={exp.title}
                            onChange={e => {
                              const newExp = [...experience];
                              newExp[i].title = e.target.value;
                              setExperience(newExp);
                            }}
                          />
                          <input
                            placeholder="Company"
                            className="bg-transparent border-b border-white/10 py-1 outline-none"
                            value={exp.company}
                            onChange={e => {
                              const newExp = [...experience];
                              newExp[i].company = e.target.value;
                              setExperience(newExp);
                            }}
                          />
                        </div>
                        <input
                          placeholder="Duration (e.g. 2021 - Present)"
                          className="w-full bg-transparent border-b border-white/10 py-1 outline-none"
                          value={exp.duration}
                          onChange={e => {
                            const newExp = [...experience];
                            newExp[i].duration = e.target.value;
                            setExperience(newExp);
                          }}
                        />
                        <textarea
                          placeholder="Highlights (Enter each bullet point on a new line)"
                          className="w-full bg-transparent border border-white/10 rounded-lg p-2 h-20 text-sm outline-none"
                          value={exp.highlights}
                          onChange={e => {
                            const newExp = [...experience];
                            newExp[i].highlights = e.target.value;
                            setExperience(newExp);
                          }}
                        />
                      </div>
                    ))}
                  </div>

                  {/* Education */}
                  <div className="space-y-4">
                    <div className="flex justify-between items-center">
                      <label className="text-sm font-medium opacity-60">Education</label>
                      <button
                        onClick={() => setEducation([...education, { degree: '', institution: '', year: '' }])}
                        className="text-xs text-purple-400 hover:text-purple-300 font-bold"
                      >
                        + Add Education
                      </button>
                    </div>
                    {education.map((edu, i) => (
                      <div key={i} className="p-4 rounded-xl bg-white/5 border border-white/10 space-y-3">
                        <input
                          placeholder="Degree (e.g. BS Computer Science)"
                          className="w-full bg-transparent border-b border-white/10 py-1 outline-none"
                          value={edu.degree}
                          onChange={e => {
                            const newEdu = [...education];
                            newEdu[i].degree = e.target.value;
                            setEducation(newEdu);
                          }}
                        />
                        <div className="grid grid-cols-2 gap-3">
                          <input
                            placeholder="Institution"
                            className="bg-transparent border-b border-white/10 py-1 outline-none"
                            value={edu.institution}
                            onChange={e => {
                              const newEdu = [...education];
                              newEdu[i].institution = e.target.value;
                              setEducation(newEdu);
                            }}
                          />
                          <input
                            placeholder="Year"
                            className="bg-transparent border-b border-white/10 py-1 outline-none"
                            value={edu.year}
                            onChange={e => {
                              const newEdu = [...education];
                              newEdu[i].year = e.target.value;
                              setEducation(newEdu);
                            }}
                          />
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Skills & Certs */}
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium opacity-60 mb-2">Skills (comma separated)</label>
                      <input
                        type="text"
                        value={skillsList}
                        onChange={(e) => setSkillsList(e.target.value)}
                        className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3"
                        placeholder="Python, React, AWS..."
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium opacity-60 mb-2">Certifications</label>
                      <input
                        type="text"
                        value={certs}
                        onChange={(e) => setCerts(e.target.value)}
                        className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3"
                        placeholder="AWS, GCP, PMP..."
                      />
                    </div>
                  </div>
                </div>
              ) : (
                <div>
                  <label className="block text-sm font-medium opacity-60 mb-2">Resume Text</label>
                  <textarea
                    value={resumeText}
                    onChange={(e) => setResumeText(e.target.value)}
                    className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 h-64 focus:ring-2 focus:ring-purple-500 transition-all outline-none resize-none leading-relaxed"
                    placeholder="Paste your current resume content here..."
                  />
                </div>
              )}


              {error && (
                <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/20 text-red-500 flex items-center gap-2">
                  <AlertCircle className="w-5 h-5" />
                  {error}
                </div>
              )}

              <button
                onClick={handleAction}
                disabled={loading || (!targetRole && activeTab !== 'generate')}
                className="w-full py-4 bg-gradient-to-r from-purple-500 via-pink-500 to-cyan-500 text-white rounded-xl font-extrabold text-lg card-shadow-purple hover:scale-[1.02] transition-all disabled:opacity-50 disabled:scale-100 flex items-center justify-center gap-2"
              >
                {loading ? (
                  <div className="w-6 h-6 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <>
                    <Sparkles className="w-5 h-5" />
                    {activeTab === 'analyze' ? "Analyze Resume" : activeTab === 'enhance' ? "Enhance Resume" : "Generate Resume"}
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Results Section */}
          <div className="space-y-6">
            {!result ? (
              // Empty State
              <div className="glass rounded-3xl p-12 text-center border border-white/10 min-h-[400px] flex flex-col items-center justify-center">
                <div className="w-20 h-20 rounded-full bg-gradient-to-br from-purple-500/20 to-pink-500/20 flex items-center justify-center mb-6">
                  <Shield className="w-10 h-10 text-purple-400 opacity-50" />
                </div>
                <h2 className="text-2xl font-bold mb-3 opacity-80">Ready to Optimize</h2>
                <p className="opacity-50 max-w-sm mx-auto">
                  Paste your resume and enter your target role to get AI-powered insights and professional improvements.
                </p>
              </div>
            ) : (
              // Results State
              <div className="animate-scale-in glass rounded-3xl p-8 card-shadow-xl border border-white/20">
                <div className="flex justify-between items-center mb-8">
                  <h2 className="text-2xl font-bold">Results</h2>
                  <div className="flex gap-2">
                    <button
                      onClick={() => generatePDF(
                        activeTab === 'analyze' ? result.analysis.summary : activeTab === 'generate' ? result.resume : result.enhanced.enhanced_resume,
                        activeTab === 'analyze' ? 'analysis' : activeTab === 'enhance' ? 'enhanced' : 'generated'
                      )}
                      className="p-2 rounded-lg bg-white/5 hover:bg-white/10 transition-colors text-purple-400"
                      title="Download Report"
                    >
                      <ArrowRight className="w-5 h-5 rotate-90" />
                    </button>
                  </div>
                </div>

                {/* Score Card (Only for Analysis) */}
                {activeTab === 'analyze' && result.analysis && (
                  <>
                    <div className="grid grid-cols-2 gap-4 mb-8">
                      <div className="p-4 rounded-xl bg-purple-500/5 border border-purple-500/10 text-center">
                        <div className="text-3xl font-bold text-purple-600 mb-1">{result.analysis.score}/100</div>
                        <div className="text-sm opacity-70">ATS Score</div>
                      </div>
                      <div className="p-4 rounded-xl bg-pink-500/5 border border-pink-500/10 text-center">
                        <div className="text-3xl font-bold text-pink-600 mb-1">{result.analysis.grade}</div>
                        <div className="text-sm opacity-70">Overall Grade</div>
                      </div>
                    </div>

                    {/* Category Breakdown */}
                    {result.analysis.categories && (
                      <div className="mb-8 space-y-3">
                        <h3 className="font-bold text-sm opacity-60 uppercase tracking-wider">Score Breakdown</h3>
                        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                          {Object.entries(result.analysis.categories).map(([cat, val]: [string, any]) => (
                            <div key={cat} className="p-3 rounded-xl bg-white/5 border border-white/5">
                              <div className="text-xs opacity-50 capitalize">{cat}</div>
                              <div className="text-lg font-bold text-purple-400">{val} pts</div>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </>
                )}

                <div className="space-y-6">
                  <div className="p-4 rounded-xl bg-black/5 border border-black/5">
                    <h3 className="font-bold mb-2 opacity-80">
                      {activeTab === 'analyze' ? "Executive Summary" : activeTab === 'generate' ? "Generated Draft" : "Enhancement Summary"}
                    </h3>
                    <p className="opacity-70 leading-relaxed whitespace-pre-line">
                      {activeTab === 'analyze'
                        ? result.analysis?.summary || "Your resume shows strong potential but needs key optimizations."
                        : activeTab === 'generate'
                          ? result.resume
                          : result.enhanced?.enhanced_resume
                      }
                    </p>
                  </div>

                  {/* Analysis Specific Details */}
                  {activeTab === 'analyze' && (
                    <div className="space-y-6">
                      {/* Strengths */}
                      {result.analysis?.strengths && (
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                          {result.analysis.strengths.map((str: string, i: number) => (
                            <div key={i} className="flex items-center gap-2 p-3 rounded-lg bg-green-500/5 text-sm">
                              <CheckCircle className="w-4 h-4 text-green-500 flex-shrink-0" />
                              <span className="opacity-80">{str}</span>
                            </div>
                          ))}
                        </div>
                      )}

                      {/* Improvements */}
                      <div className="space-y-3">
                        <h3 className="font-bold opacity-80">Key Improvements Needed</h3>
                        {result.analysis?.improvements?.map((imp: string, i: number) => (
                          <div key={i} className="flex items-start gap-3 p-3 rounded-lg bg-red-500/5 text-sm">
                            <AlertCircle className="w-4 h-4 text-red-500 mt-0.5 flex-shrink-0" />
                            <span className="opacity-80">{imp}</span>
                          </div>
                        ))}
                      </div>

                      {/* Keywords Missing */}
                      {result.analysis?.keywords_missing && result.analysis.keywords_missing.length > 0 && (
                        <div className="p-4 rounded-xl bg-yellow-500/5 border border-yellow-500/10">
                          <h3 className="font-bold text-sm text-yellow-500 mb-3 flex items-center gap-2">
                            <Sparkles className="w-4 h-4" />
                            Optimization Keywords Needed
                          </h3>
                          <div className="flex flex-wrap gap-2">
                            {result.analysis.keywords_missing.map((kw: string) => (
                              <span key={kw} className="px-2 py-1 rounded-md bg-yellow-500/10 text-yellow-500 text-xs font-semibold">
                                {kw}
                              </span>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  )}

                  {/* Success Message for Enhance */}
                  {activeTab === 'enhance' && (
                    <div className="p-6 rounded-xl bg-green-500/10 border border-green-500/20 text-center">
                      <CheckCircle className="w-12 h-12 text-green-500 mx-auto mb-4" />
                      <h3 className="text-xl font-bold text-green-600 mb-2">Resume Enhanced Successfully!</h3>
                      <p className="opacity-70 mb-4">
                        Your resume has been rewritten to perfectly match the <strong>{targetRole}</strong> role.
                      </p>
                      <button
                        onClick={() => generatePDF(result.enhanced?.enhanced_resume, 'enhanced')}
                        className="w-full py-3 bg-green-600 hover:bg-green-700 text-white rounded-xl font-bold transition-all flex items-center justify-center gap-2"
                      >
                        <ArrowRight className="w-5 h-5 rotate-90" />
                        Download Enhanced Resume
                      </button>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}